//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_Chargue_Catalogs_MC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_AWB_VPM
    {
        public int id_CatAWB { get; set; }
        public string AWB_Number { get; set; }
        public string Agent_Code { get; set; }
        public string Agent_Name { get; set; }
        public Nullable<System.DateTime> DayInsertArchive { get; set; }
    }
}
