//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_Chargue_Catalogs_MC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Fechas_MC
    {
        public int id_fecha { get; set; }
        public Nullable<System.DateTime> DayInsertArchive { get; set; }
        public Nullable<System.DateTime> StartDayInsertArchive { get; set; }
        public Nullable<System.DateTime> EndDayInsertArchive { get; set; }
        public Nullable<System.DateTime> Start_STD_LOCAL_Date { get; set; }
        public Nullable<System.DateTime> End_STD_LOCAL_Date { get; set; }
    }
}
