//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_Chargue_Catalogs_MC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Stations_M
    {
        public int idStation { get; set; }
        public string STATION { get; set; }
        public string DESC_CITY { get; set; }
        public string DESC_AIRPORTS { get; set; }
        public string DESC_COUNTRY { get; set; }
        public string ID_ZONE { get; set; }
        public Nullable<double> HORA_Z { get; set; }
        public string DIF_MEX { get; set; }
        public Nullable<double> NUM { get; set; }
        public Nullable<double> HRS { get; set; }
        public string GHA { get; set; }
        public string DETALLE1 { get; set; }
        public string DETALLE2 { get; set; }
        public string DETALLE3 { get; set; }
        public string DETALLE4 { get; set; }
        public string DETALLE5 { get; set; }
        public string REGION1 { get; set; }
        public string REGION2 { get; set; }
        public string CAMPOS_A_MODIFICAR { get; set; }
    }
}
