//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Process_Chargue_Catalogs_MC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BI_TableauEntities : DbContext
    {
        public BI_TableauEntities()
            : base("name=BI_TableauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_AWB_VPM> CAT_AWB_VPM { get; set; }
        public virtual DbSet<Cat_Fechas_MC> Cat_Fechas_MC { get; set; }
        public virtual DbSet<Cat_Stations_M> Cat_Stations_M { get; set; }
    }
}
